on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: node server.js 